Rewards:
  boss:
    gamemode adventure %player_name%:
      Display Name: <rainbow> Quest Reward
      Lore:
        - hello
        - <red> ello
        -
        - <green> click to open
      item: red_stained_glass_pane
    gamemode survival %player_name%:
      Display Name: <rainbow> Quest Reward 2
      Lore:
        - hello
        - <red> ello
        -
        - <green> click to open
      item: red_stained_glass_pane
  killed:
    gamemode adventure %player_name%:
      Display Name: <rainbow> Quest Reward
      Lore:
        - hello
        - <red> ello
        -
        - <green> click to open
      item: red_stained_glass_pane
    gamemode survival %player_name%:
      Display Name: <rainbow> Quest Reward 2
      Lore:
        - hello
        - <red> ello
        -
        - <green> click to open
      item: red_stained_glass_pane
  fished:
    gamemode adventure %player_name%:
      Display Name: <rainbow> Quest Reward
      Lore:
        - hello
        - <red> ello
        -
        - <green> click to open
      item: red_stained_glass_pane
  hostiles:
    gamemode adventure %player_name%:
      Display Name: <rainbow> Quest Reward
      Lore:
        - hello
        - <red> ello
        -
        - <green> click to open
      item: red_stained_glass_pane
  event:
    gamemode adventure %player_name%:
      Display Name: <rainbow> Quest Reward
      Lore:
        - hello
        - <red> ello
        -
        - <green> click to open
      item: red_stained_glass_pane
  mined:
    gamemode adventure %player_name%:
      Display Name: <rainbow> Quest Reward
      Lore:
        - hello
        - <red> ello
        -
        - <green> click to open
      item: red_stained_glass_pane
  built:
    gamemode adventure %player_name%:
      Display Name: <rainbow> Quest Reward
      Lore:
        - hello
        - <red> ello
        -
        - <green> click to open
      item: red_stained_glass_pane
Milestones:
  killed:
    - 10
    - 100
    - 200
    - 500
    - 1000
  fished:
    - 10
    - 100
    - 200
    - 500
    - 1000
  hostiles:
    - 10
    - 100
    - 200
    - 500
    - 1000
  event:
    - 10
    - 100
    - 200
    - 500
    - 1000
  mined:
    - 10
    - 100
    - 200
    - 500
    - 1000
  built:
    - 10
    - 100
    - 200
    - 500
    - 1000
